# zlib
set (MIF_ZLIB_LOCAL_PATH "${THITD_PARTY_SOURCES_PATH}/zlib/")

# boost
set (MIF_BOOST_LOCAL_PATH "${THITD_PARTY_SOURCES_PATH}/boost/")

# jsoncpp
set (MIF_JSONCPP_LOCAL_PATH "${THITD_PARTY_SOURCES_PATH}/jsoncpp/")

# libpq
set (MIF_LIBPQ_LOCAL_PATH "${THITD_PARTY_SOURCES_PATH}/libpq/")

# pugixml
set (MIF_PUGIXML_LOCAL_PATH "${THITD_PARTY_SOURCES_PATH}/pugixml/")
